#!/bin/bash

set -e

adjust() {
  for id in $(xinput --list --id-only); do
    if xinput --list --name-only "$id" | grep 'ipts 1B96:001F Pen' > /dev/null; then
      set +e
      xinput set-prop "$id" 'Coordinate Transformation Matrix' "$@" 2>/dev/null
      set -e
    fi
  done
}

# connected to the monitor?
if xrandr --query | grep ''3840x2160 > /dev/null; then
  # 2736/(2736+3840) and
  # 1824/2160
  adjust 0.41605839416058393 0 0 0 0.8444444444444444 0 0 0 1
else
  adjust 1 0 0 0 1 0 0 0 1
fi

exit 0
