#!/bin/bash

sudo apt update
sudo apt install ibus-hangul ibus-gtk3 ibus-gtk im-config

cat > $HOME/.xinputrc <<END
if [[ \$SHELL == "/bin/zsh" || \$SHELL == "/usr/bin/zsh" ]]
then
  setopt nonomatch
fi
run_im ibus
END

cat >> "$MSGFILE" <<EOF
Run ibus-setup to configure ibus-hangul (after logging in again)
EOF

exit 0
