#!/bin/bash

set -e

CONFDIR=${SETUPDIR}/autopkg
DESTDIR=$HOME/.autopkg/config/jangho
mkdir -p "$DESTDIR"
ln -s "$CONFDIR"/git.json "$DESTDIR"/git.json
ln -s "$CONFDIR"/targets.json "$DESTDIR"/targets.json

exit 0
