#!/bin/bash

set -e

vercmp() {
  local a
  local b
  a=$(pacman -Sl | grep " $1 " | cut -d' ' -f3 | cut -d'-' -f1)
  b=$(pacman -Sl | grep " $2 " | cut -d' ' -f3 | cut -d'_' -f1)
  if [[ "$a" != "$b" ]]; then
    cat >> "$MSGFILE" <<EOF
PKGBUILD update needed: ${a}(${1}) != ${b}(${2})
EOF
  fi
}

autopkg update
rsync -avz --delete "$HOME"/.autopkg/repository/autopkg/ \
  mango.vanilla.jangho.io:/srv/data/autopkg/
sudo pacman -Syu --needed --noconfirm

vercmp 'linux' 'linux-surface-pro-2017'
vercmp 'libwacom' 'libwacom-surface-pro-2017'

if ! autopkg has-no-autoremovable; then
  cat >> "$MSGFILE" <<EOF
autopkg: There are auto-removable package(s).
EOF
fi

exit 0
