#!/bin/bash

CONF=${SETUPDIR}/vim/vimrc
ln -s $CONF $HOME/.vimrc

curl -fLo ~/.vim/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
vim +PlugUpdate +qall

exit 0
