" General
set encoding=utf-8
set nocompatible
filetype plugin indent on

" Plugins
call plug#begin('~/.vim/plugged')
Plug 'evanmiller/nginx-vim-syntax'
Plug 'stephpy/vim-yaml'
Plug 'Yggdroot/indentLine'
Plug 'tpope/vim-fugitive'
Plug 'vim-airline/vim-airline'
Plug 'vim-airline/vim-airline-themes'
Plug 'scrooloose/nerdtree'
Plug 'tpope/vim-surround'
Plug 'jiangmiao/auto-pairs'
Plug 'cbracken/vala.vim'
Plug 'leafgarland/typescript-vim'
Plug 'editorconfig/editorconfig-vim'
Plug 'lervag/vimtex'

" vim-airline
set laststatus=2
set noshowmode
set t_Co=256
let g:airline_theme='badwolf'
let g:airline#extensions#tabline#enabled = 0
let g:airline_powerline_fonts = 1

" indentLine
let g:indentLine_color_term = 239
let g:indentLine_color_gui = '#AAAAAA'
let g:indentLine_char = '│'

" editorconfig
let g:EditorConfig_exclude_patterns = ['fugitive://.*', 'scp://.*']

" Indent
set shiftwidth=2
set softtabstop=2
set expandtab
set autoindent
set smartindent
set breakindent

" Interface
syntax on
color desert
set visualbell
set mouse=a
set showcmd
set number
set numberwidth=5
set matchpairs+=“:”
set matchpairs+=‘:’
set showmatch
au BufEnter,WinEnter * match ErrorMsg '\s\+$'
  " highlight trailing whitespace
set backspace=indent,eol,start
  " allow backspacing over everything in insert mode

" Search
set hlsearch
set nowrapscan
set ignorecase
map <space> /

" Hot keys
vmap <Tab> >gv
vmap <S-Tab> <gv
map <F2> :NERDTreeToggle<CR>

" Load addins
for addin in split(globpath('~/.setup/this', '**/vimrc_addin'), '\n')
  exec "source ".addin
endfor

" Plugins
call plug#end()
