#!/bin/bash

set -e

LINUX_PACKAGENAME="$1"

V="$(pacman -Q "$LINUX_PACKAGENAME" | cut -d' ' -f2 | cut -d- -f1 | cut -d_ -f1)"
INSTALLED_KERNEL="$(echo "$V" | cut -d. -f1).$(echo "$V" | cut -d. -f2).$(echo "$V" | cut -d. -f3)"
RUNNING_KERNEL="$(uname -r | cut -d- -f1)"
if [[ "$INSTALLED_KERNEL" != "$RUNNING_KERNEL" ]]; then
  echo "Reboot to apply kernel update: $RUNNING_KERNEL -> $INSTALLED_KERNEL" >> "$MSGFILE"
fi

exit 0
