#!/usr/bin/zsh

set -euo pipefail

if [[ "$1" == 'i' ]]; then
  user="${2##*/}"
  echo "$user"
  echo -n "$user" | tr -d '\n' | wl-copy
  read -k1 -s
  /usr/bin/pass show "$2" | head -n1 | tr -d '\n' | wl-copy
  echo "Copied password for $2"
  if [[ -f "$HOME/.password-store/$2/otp.gpg" ]]; then
    echo -n 'OTP: '
    read -k1 -s
    otp=$(/usr/bin/pass otp "$2/otp")
    echo "$otp"
    echo -n "$otp" | tr -d '\n' | wl-copy
  else
    echo -n 'Clear clipbaord: '
    read -k1 -s
    echo -n ' ' | wl-copy
    echo 'done'
  fi
else
  /usr/bin/pass "$@"
fi

exit 0
