#!/bin/bash

set -e

ENCF=$(dirname "$(readlink -f "$0")")/../share/dropbear-encrypt
[[ -z "$1" ]] && exit 1
ADDR=$(awk "{if (\$1==\"$1\") print \$2}" "$ENCF")
[[ -z "$ADDR" ]] && exit 1
exec ssh "$ADDR" -p50222 -lroot -i"$HOME"/.secret/local/dropbear-encrypt-user -oUserKnownHostsFile="$HOME"/.secret/dropbear-encrypt/known_hosts
