#!/bin/bash

set -e

CONFHOME=$(dirname $(dirname "$(realpath -s "$0")"))
PIESCONF=$CONFHOME/pies.conf
PIECONF=$CONFHOME/gnome-pie.conf
AUTOSTARTCONF=$CONFHOME/../gnome-pie.desktop
AUTOSTARTDIR=${XDG_CONFIG_HOME:=$HOME/.config}/autostart
CONFIGDIR=${XDG_CONFIG_HOME:=$HOME/.config}/gnome-pie
mkdir -p "$AUTOSTARTDIR"
mkdir -p "$CONFIGDIR"
ln -s "$AUTOSTARTCONF" "$AUTOSTARTDIR"
ln -s "$PIESCONF" "$CONFIGDIR"
ln -s "$PIECONF" "$CONFIGDIR"

exit 0
