#!/bin/bash

set -e

echo "https://software.opensuse.org/ymp/home:GNorth:Arc_and_Papirus/openSUSE_Tumbleweed/papirus-icon-theme.ymp?base=openSUSE%3AFactory&query=papirus-icon-theme" >> "$MSGFILE"
echo "https://software.opensuse.org/ymp/home:jangho/openSUSE_Tumbleweed/gnome-pie.ymp?base=openSUSE%3AFactory&query=gnome-pie" >> "$MSGFILE"

sudo zypper in zenity

exit 0
