#!/usr/bin/zsh
[[ -e /usr/lib/jvm/default ]] && export JAVA_HOME=/usr/lib/jvm/default
[[ -f /opt/protobuf-for-onyx/environment ]] && . /opt/protobuf-for-onyx/environment
[[ -f /opt/hadoop-for-onyx/environment ]] && . /opt/hadoop-for-onyx/environment
[[ -f /opt/anaconda/bin/activate ]] && alias anaconda-activate='source /opt/anaconda/bin/activate root'
[[ -f /opt/anaconda/bin/deactivate ]] && alias anaconda-deactivate='source /opt/anaconda/bin/deactivate root'

spl-get-metric-from-log() {
  local logpath="$1"
  grep "INFO master.MetricManagerMaster:" "$logpath" | cut -b52-
}

spl-get-inputreadtime-from-log() {
  spl-get-metric-from-log "$1" | grep vertex-"${2:=4}"_ | awk '{if (match($0, /InputReadTime\(ms\)":([0-9])+/, m)){print m[0]}}' | cut -b20-
}

spl-parse-metric-from-log() {
  local logpath="$1"
  local tmp
  tmp="$(mktemp)"
  spl-get-metric-from-log "$logpath" > "$tmp"
  ~/workspace/spl/nemo/bin/metric-parser.py "$tmp"
}

spl-pull-logs-from-orange() {
  rsync -avz --exclude='*.jar' ubuntu@orange.jangho.io:~/setup/logs/ ./
}
