#!/bin/bash

CONF=$(dirname $(dirname "$(realpath -s "$0")"))/conky.conf
CONFIGDIR=${XDG_CONFIG_HOME:=$HOME/.config}/conky
mkdir -p "$CONFIGDIR"
ln -s "$CONF" "$CONFIGDIR"

ASCONF=$(dirname $(dirname "$(realpath "$0")"))/conky.desktop
ASCONFIGDIR=${XDG_CONFIG_HOME:=$HOME/.config}/autostart
mkdir -p "$ASCONFIGDIR"
ln -s "$ASCONF" "$ASCONFIGDIR"

exit 0
