#!/bin/bash

pacaur --needed -Sy noto-fonts noto-fonts-cjk ttf-nanumgothic_coding ttf-hack emojione-color-font ttf-dejavu

sudo rm -f /etc/fonts/conf.d/{56-emojione-color-font.conf,64-ttf-emojione-color.conf}

exit 0
