#!/bin/bash

sudo apt-add-repository ppa:eosrei/fonts
sudo apt update
sudo apt install fonts-noto fonts-emojione-svginot fonts-noto-cjk fonts-nanum-coding fonts-hack-ttf fonts-dejavu-core

sudo rm /etc/fonts/conf.d/56-emojione-color.conf

exit 0
