#!/bin/bash

set -euo pipefail

FILENAME=$1

curl 'http://10.11.99.1/upload' -H 'Origin: http://10.11.99.1' -H 'Accept: */*' -H 'Referer: http://10.11.99.1/' -H 'Connection: keep-alive' -F "file=@${FILENAME};filename=${FILENAME};type=application/pdf"
