#!/bin/bash

set -euo pipefail

NOW=$(date --iso-8601=seconds)
TMP=$(mktemp -d)
TODAY=$(ssh jangho@mango.jangho.io -p50022 -- "/opt/mango/today/today")
cd "${TMP}"
echo -e "---\nmainfont: Noto Serif CJK KR\n---\n${TODAY}" | pandoc --pdf-engine=wkhtmltopdf -f markdown -t html -o "today.pdf" --metadata pagetitle="Today ${NOW}"
curl 'http://10.11.99.1/upload' -H 'Origin: http://10.11.99.1' -H 'Accept: */*' -H 'Referer: http://10.11.99.1/' -H 'Connection: keep-alive' -F "file=@today.pdf;filename=today.${NOW}.pdf;type=application/pdf"
