#!/bin/bash

set -euo pipefail

TODAY=$(ssh jangho@mango.jangho.io -p50022 -- "/opt/mango/today/today")
echo -e "---\nmainfont: Noto Serif CJK KR\n---\n${TODAY}" | pandoc --pdf-engine=xelatex -o "today.$(date --iso-8601=seconds).pdf"
