#!/bin/bash

set -e

CONF=${SETUPDIR}/mimeapps/mimeapps.list
TARGET=${XDG_CONFIG_HOME:=$HOME/.config}/mimeapps.list
if [[ -f "$TARGET" ]]; then
  echo "Old content in ${TARGET}:" >> "$MSGFILE"
  cat "$TARGET" >> "$MSGFILE"
fi
ln -sf "$CONF" "$TARGET"

exit 0
