#!/bin/bash

wdir=$(pwd)

cd "$HOME"/.gitit.repo
git pull origin master
read -r -p "Compile gitit and upload to papaya? [y/N]" response
if [[ $response =~ ^([yY][eE][sS]|[yY])$ ]]
then
  stack setup
  stack install
  rsync -avz --delete ~/.gitit.repo jangho@papaya.jangho.kr:~
  rsync -avz --delete ~/.stack jangho@papaya.jangho.kr:~
  rsync -avz ~/.local/bin/gitit jangho@papaya.jangho.kr:~/.local/bin
  rsync -avz ~/.local/bin/expireGititCache jangho@papaya.jangho.kr:~/.local/bin
fi

cd "$wdir"
