#!/usr/bin/zsh

set -e

GITPATH=$(git rev-parse --show-toplevel)
DIR=~/.remote-maven/$(hostname)$GITPATH

if [[ "$1" == '--shell' ]]; then
  ssh -t pear.jangho.io -p50023 -- "cd \"$DIR\"; $SHELL"
  exit 0
fi

function cleanup {
  set +e
  ssh pear.jangho.io -p50023 -- jps | awk '"'"'{print $1}'"'"' | xargs -L1 -- kill -9
  exit $1
}

trap 'cleanup $?' EXIT

cd "$GITPATH"
ssh pear.jangho.io -p50023 -- rm -rf \"$DIR\"
ssh pear.jangho.io -p50023 -- mkdir -p \"$DIR\"
rsync -avz --delete -0 --files-from <(git ls-files -z) -e 'ssh -p50023' . "pear.jangho.io:$DIR"
ssh -t pear.jangho.io -p50023 -- "cd \"$DIR\" && pwd && /usr/bin/mvn $@"
exit 0
