#!/bin/bash

current_tracking="$(timew)"
current_tracking_exit=$?

if [[ $current_tracking_exit -eq 0 ]]
then
  zenity --question --text="$current_tracking""\nCancel current tracking?" --title="Pomodoro" --icon-name=gnome-pomodoro
  cancel_tracking_exit=$?
  [[ cancel_tracking_exit -ne 0 ]] && exit 1
fi

timew stop
killall jangho-pomodoro
killall_exit=$?
[[ $killall_exit -eq 0 || $current_tracking_exit -eq 0 ]] && exit 0

pomodoro_task="$(zenity --entry --title="Starting Pomodoro" --text="$(timew summary :day)")"
input_success=$?
if [[ $input_success -eq 0 ]]
then
  if [[ "$pomodoro_task" == "" ]]
  then
    timew continue
    timew_exit=$?
    if [[ timew_exit -eq 255 ]]
    then
      zenity --error --title="Pomodoro" --text="There is no previous tracking to continue."
      exit 1
    fi
  else
    timew start "$pomodoro_task"
  fi
  exec "$HOME"/.setup/gnome-pie/scripts/jangho-pomodoro
else
  exit 1
fi
