#!/bin/bash

DIR=~/archive/"$(date +%Y/%m)"

mkdir -p "$DIR"
if command -v nautilus > /dev/null; then
  exec nautilus "$DIR"
fi
if command -v gio > /dev/null; then
  exec gio open "$DIR"
fi
exec xdg-open "$DIR"
