#!/bin/bash

set -e

if [[ $(gsettings get org.gnome.desktop.peripherals.touchpad send-events) == "'enabled'" ]]; then
  echo 'disabling...'
  gsettings set org.gnome.desktop.peripherals.touchpad send-events disabled
else
  echo 'enabling...'
  gsettings set org.gnome.desktop.peripherals.touchpad send-events enabled
fi

exit 0
