#!/bin/bash

# ./toggle-touchpad: toggle
# ./toggle-touchpad enable: enable

set -e

if [[ $(gsettings get org.gnome.desktop.peripherals.touchpad send-events) == "'enabled'" ]]; then
  if [[ "$1" != 'enable' ]]; then
    echo 'disabling...'
    gsettings set org.gnome.desktop.peripherals.touchpad send-events disabled
    notify-send --urgency=low --expire-time=100 --icon=touchpad-disabled-symbolic Touchpad\ disabled
  fi
else
  echo 'enabling...'
  gsettings set org.gnome.desktop.peripherals.touchpad send-events enabled
  notify-send --urgency=low --expire-time=100 --icon=input-touchpad-symbolic Touchpad\ enabled
fi

exit 0
