#!/bin/bash

set -e

cd $HOME/.gitit/gitit
git pull
stack install --local-bin-path $HOME/.gitit/bin
rsync -avz $HOME/.gitit/bin guava.jangho.io:/home/jangho/.local/bin
ssh guava.jangho.io -- sudo systemctl restart gitit-jangho@journal

cat >> "$MSGFILE" <<EOF
Check updates for Canta theme https://github.com/vinceliuice/Canta-theme
EOF

exit 0
