#!/bin/bash

set -e

if vboxmanage showvminfo lemon | grep --color=no -e "State:"| grep off > /dev/null; then
  exit 0
else
  if [[ "$1" == '--notify-send' ]]; then
    notify-send -i virtualbox 'Power off lemon first' 'Power off lemon before shutting down pear'
  else
    >&2 echo "Power off lemon first"
  fi
  exit 1
fi
