#!/bin/bash

set -e

function rmver {
  rm -rf /srv/data/"$1"/.stversions
  mkdir /srv/data/"$1"/.stversions
  chown jangho:jangho /srv/data/"$1"/.stversions
  chmod 755 /srv/data/"$1"/.stversions
}

echo -n 'Stopping Syncthing...'
sudo systemctl stop syncthing@jangho
echo ' done'

echo -n 'Removing Syncthing revision copies...'
rmver Archive
rmver Clone/mango
rmver Clone/gooseberry
rmver Music
rmver git
echo ' done'

echo 'Taking a snapshot:'
sudo btrfs subvolume snapshot -r /srv/data "/srv/snapshots/$(date +%Y-%m-%dT%H:%M:%S%:z)"

echo -n 'Starting Syncthing...'
sudo systemctl start syncthing@jangho
echo ' done'

echo 'List of subvolumes:'
sudo btrfs subvolume list /srv/snapshots

exit 0
