#!/bin/bash

set -e

function rmver {
  rm -rf /srv/data/"$1"/.stversions
  mkdir /srv/data/"$1"/.stversions
  chown jangho:jangho /srv/data/"$1"/.stversions
  chmod 755 /srv/data/"$1"/.stversions
}

echo -n 'Stopping Syncthing...'
sudo systemctl stop syncthing@jangho
echo ' done'

echo -n 'Removing Syncthing revision copies...'
rmver Archive
rmver Clone/guava
rmver Clone/mango
rmver Music
rmver git
rmver gitit
echo ' done'

echo -n 'Taking a snapshot...'
sudo btrfs subvolume snapshot -r /srv/data "/srv/snapshots/$(date +%Y-%m-%dT%H:%M:%S%:z)"
echo ' done'

echo -n 'Starting Syncthing...'
sudo systemctl start syncthing@jangho
echo ' done'

echo 'List of subvolumes:'
sudo btrfs subvolume list /srv/data

exit 0
