#!/bin/bash

set -e

echo 'Taking a snapshot:'
sudo btrfs subvolume snapshot -r /srv/data "/srv/snapshots/$(date +%Y-%m-%dT%H:%M:%S%:z)"

echo 'List of subvolumes:'
sudo btrfs subvolume list /srv/snapshots

exit 0
