#!/bin/zsh

MODE=$argv[1]

# Plugins
source ~/.zplug/init.zsh
zplug "robbyrussell/oh-my-zsh", use:"oh-my-zsh.sh"
zplug "plugins/git", from:oh-my-zsh
zplug "zsh-users/zsh-syntax-highlighting"
zplug "zsh-users/zsh-completions"
zplug "zsh-users/zsh-autosuggestions"
zplug "caiogondim/bullet-train-oh-my-zsh-theme", as:theme
zplug "junegunn/fzf", use:"shell/*.zsh", defer:1
zplug "junegunn/fzf-bin", from:gh-r, as:command, rename-to:fzf, use:"*linux*amd64*"

# oh-my-zsh
DISABLE_AUTO_UPDATE=true

# TERM
[[ -z "$TMUX" ]] || export TERM=screen-256color

# bullet-train
BULLETTRAIN_PROMPT_ROOT=false
BULLETTRAIN_PROMPT_CHAR="➜"
BULLETTRAIN_PROMPT_ADD_NEWLINE=false
BULLETTRAIN_STATUS_EXIT_SHOW=true
BULLETTRAIN_STATUS_BG='red'
BULLETTRAIN_PROMPT_ORDER=(status custom conditional_perl conditional_ruby virtualenv conditional_nvm go dir git hg)
function prompt_conditional_perl() {
  if [[ $BULLETTRAIN_PERL_SHOW == true ]]
  then
    prompt_perl
  fi
}
function prompt_conditional_nvm() {
  if [[ $BULLETTRAIN_NVM_SHOW == true ]]
  then
    prompt_nvm
  fi
}
function prompt_conditional_ruby() {
  if [[ $BULLETTRAIN_RBENV_SHOW == true ]]
  then
    prompt_ruby
  fi
}
BULLETTRAIN_DIR_EXTENDED=2
if [[ $USERNAME != 'jangho' && $USERNAME != 'janghose' ]]
then
  BULLETTRAIN_CUSTOM_MSG_USERNAME='%n'
else
  BULLETTRAIN_CUSTOM_MSG_USERNAME=''
fi
if (($+SSH_TTY))
then
  BULLETTRAIN_CUSTOM_MSG_HOSTNAME='%m'
else
  BULLETTRAIN_CUSTOM_MSG_HOSTNAME=''
fi
if [[ $BULLETTRAIN_CUSTOM_MSG_USERNAME != '' && $BULLETTRAIN_CUSTOM_MSG_HOSTNAME != '' ]]
then
  BULLETTRAIN_CUSTOM_MSG_AT='@'
else
  BULLETTRAIN_CUSTOM_MSG_AT=''
fi
if [[ $BULLETTRAIN_CUSTOM_MSG_USERNAME != '' || $BULLETTRAIN_CUSTOM_MSG_HOSTNAME != '' ]]
then
  BULLETTRAIN_CUSTOM_MSG=$BULLETTRAIN_CUSTOM_MSG_USERNAME$BULLETTRAIN_CUSTOM_MSG_AT$BULLETTRAIN_CUSTOM_MSG_HOSTNAME
fi
if [[ $UID -eq 0 ]]
then
  BULLETTRAIN_CUSTOM_BG='red'
fi

# zsh-autosuggest style
ZSH_AUTOSUGGEST_HIGHLIGHT_STYLE='fg=242'

# ~/.local/bin
export PATH=$HOME/.local/bin:$PATH

# history
SAVEHIST=10000
HISTSIZE=10000
HISTFILE=~/.zsh_history
setopt hist_ignore_all_dups
setopt hist_ignore_space

# switch ctrl+l <=> ctrl+space
bindkey "^L" forward-word
bindkey "^@" clear-screen

# aliases
alias ls='ls --color=auto'
alias mv='mv -i'
alias cp='cp -i'
alias rm='rm -i'
alias spwgen='pwgen -y -1 40 5'

alias b='mvn clean install'
alias bb='mvn clean install -DskipTests'
alias bbb='mvn clean install -DskipTests -TC1 -P!code-quality'

# ssh
alias mango='ssh -p50022 jangho@mango.jangho.io'
alias martini='ssh janghose@martini.snucse.org'
alias guava='ssh jangho@guava.jangho.io'
alias dev='ssh jangho@dev.snucse.org'
alias cms='ssh jangho@cmscluster.snu.ac.kr'
alias socks='ssh -f -D 8080 -C -q -N cmscluster.snu.ac.kr'
alias awsocks='ssh -f -D 9090 -C -q -N ubuntu@35.164.221.40'
alias am='ssh ubuntu@35.164.221.40'
alias mm='ssh ubuntu@34.210.48.245'

# cd to month
alias month="cd ~/archive/$(date +%Y/%m)"

# update
alias update='~/.setup/setup --update'
alias ㄷ핑ㅓㅕ='update'
alias ㄴ='s'
alias ㅓ='t'

# encrypt
function encrypt {
  gpg --encrypt --output "$1".gpg --encrypt --recipient jangho@jangho.io "$1"
  rm -i "$1"
}

# folder digest
function fdigest {
  find . -type f -print0 | xargs -L1 -0 -- md5sum | sort | md5sum
  find . | sort | md5sum
}

# addins before loading plugins
while read -r addin
do
  source $addin
done <<<$(find -L $HOME/.setup/this -name "zshrc_addin_pre")

# Manage plugins
if [[ $MODE == '--manage-only' ]]
then
  zplug clean
  zplug update
  zplug install
  exit 0
fi
if [[ $MODE == '--install-only' ]]
then
  zplug install
  exit 0
fi
zplug check --verbose || zplug install
zplug load

# addins after loading plugins
while read -r addin
do
  source $addin
done <<<$(find -L $HOME/.setup/this -name "zshrc_addin_post")
