#!/bin/zsh

MODE=$argv[1]

# Plugins
source ~/.zplug/init.zsh
zplug "robbyrussell/oh-my-zsh", use:"oh-my-zsh.sh"
zplug "plugins/git", from:oh-my-zsh
zplug "plugins/svn", from:oh-my-zsh
zplug "zsh-users/zsh-syntax-highlighting"
zplug "zsh-users/zsh-completions"
zplug "zsh-users/zsh-autosuggestions"
zplug "caiogondim/bullet-train-oh-my-zsh-theme", as:theme
zplug "junegunn/fzf", use:"shell/*.zsh", defer:1

# oh-my-zsh
DISABLE_AUTO_UPDATE=true

# TERM
[[ -z "$TMUX" ]] || export TERM=screen-256color

# ls
export LS_COLORS=$(vivid generate jangho)

# bullet-train
BULLETTRAIN_DIR_BG='#cc3f29'
BULLETTRAIN_PROMPT_ROOT=false
BULLETTRAIN_PROMPT_CHAR="➜"
BULLETTRAIN_PROMPT_ADD_NEWLINE=false
BULLETTRAIN_STATUS_EXIT_SHOW=true
BULLETTRAIN_STATUS_BG='red'
BULLETTRAIN_PROMPT_ORDER=(status custom btrfs_scrub conditional_perl conditional_ruby virtualenv conditional_nvm go dir git hg svn)
function prompt_btrfs_scrub() {
  :
}
function prompt_svn() {
  local svn_nr
  if in_svn; then
    if [[ $(svn_dirty_choose_pwd dirty clean) == 'dirty' ]]; then
      prompt_segment white red
      echo -n '✘'
    else
      prompt_segment white green
      echo -n '✔'
    fi
  fi
}
function prompt_conditional_perl() {
  if [[ $BULLETTRAIN_PERL_SHOW == true ]]
  then
    prompt_perl
  fi
}
function prompt_conditional_nvm() {
  if [[ $BULLETTRAIN_NVM_SHOW == true ]]
  then
    prompt_nvm
  fi
}
function prompt_conditional_ruby() {
  if [[ $BULLETTRAIN_RBENV_SHOW == true ]]
  then
    prompt_ruby
  fi
}
BULLETTRAIN_DIR_EXTENDED=2
if [[ $USERNAME != 'jangho' && $USERNAME != 'janghose' ]]
then
  BULLETTRAIN_CUSTOM_MSG_USERNAME='%n'
else
  BULLETTRAIN_CUSTOM_MSG_USERNAME=''
fi
if (($+SSH_TTY))
then
  BULLETTRAIN_CUSTOM_MSG_HOSTNAME='%m'
else
  BULLETTRAIN_CUSTOM_MSG_HOSTNAME=''
fi
if [[ $BULLETTRAIN_CUSTOM_MSG_USERNAME != '' && $BULLETTRAIN_CUSTOM_MSG_HOSTNAME != '' ]]
then
  BULLETTRAIN_CUSTOM_MSG_AT='@'
else
  BULLETTRAIN_CUSTOM_MSG_AT=''
fi
if [[ $BULLETTRAIN_CUSTOM_MSG_USERNAME != '' || $BULLETTRAIN_CUSTOM_MSG_HOSTNAME != '' ]]
then
  BULLETTRAIN_CUSTOM_MSG=$BULLETTRAIN_CUSTOM_MSG_USERNAME$BULLETTRAIN_CUSTOM_MSG_AT$BULLETTRAIN_CUSTOM_MSG_HOSTNAME
fi
if [[ $UID -eq 0 ]]
then
  BULLETTRAIN_CUSTOM_BG='red'
fi

# zsh-autosuggest style
ZSH_AUTOSUGGEST_HIGHLIGHT_STYLE='fg=242'

# ~/.local/bin
export PATH=$HOME/.local/bin:$PATH

# history
SAVEHIST=10000
HISTSIZE=10000
HISTFILE=~/.zsh_history
setopt hist_ignore_all_dups
setopt hist_ignore_space

# switch ctrl+l <=> ctrl+space
bindkey "^L" forward-word
bindkey "^@" clear-screen

# aliases
alias ls='ls --color=auto'
alias mv='mv -i'
alias cp='cp -i'
alias rm='rm -i'
function note {
  ssh jangho@mango.jangho.io -p50022 -- "/opt/mango/sendmail/note \"$@\""
}
function diary {
  ssh jangho@mango.jangho.io -p50022 -- "/opt/mango/sendmail/diary \"$@\""
}
alias today='ssh jangho@mango.jangho.io -p50022 -- "/opt/mango/today/today"'
alias b='mvn clean install'
alias bb='mvn install -TC1 -DskipTests -Dmaven.test.skip -Dcheckstyle.skip -P!code-quality -Drat.skip'

# ssh
alias mango='ssh -p50022 jangho@mango.jangho.io'
alias mango-data='mkdir -p ~/mango && sshfs mango.jangho.io:/srv/data ~/mango'
alias mango-data-umount='fusermount -u ~/mango && rmdir ~/mango'

# cd to month
alias month="cd ~/archive/$(date +%Y/%m)"

# update
alias update='~/.setup/setup --update'
alias ㄷ핑ㅓㅕ='update'

# encrypt
function encrypt {
  gpg --encrypt --output "$1".gpg --encrypt --recipient \
    EE37EBD527ECFE87A96A7BDB6503B6817E24FCA3 "$1" && chmod --reference="$1" "$1".gpg && rm -i "$1"
}

# sshuttle
# usage: sshuttle-private ubuntu@cmscluster.snu.ac.kr:2222 -H
function sshuttle-private {
  sshuttle ${@:2} -r "$1" 192.168.0.0/16 172.16.0.0/12 10.0.0.0/8 -x $(echo "$1" | cut -d'@' -f2 | cut -d':' -f1)/32
}
# usage: sshuttle-proxy ubuntu@cmscluster.snu.ac.kr:2222
function sshuttle-proxy {
  sshuttle ${@:2} -r "$1" 0/0 -x $(echo "$1" | cut -d'@' -f2 | cut -d':' -f1)/32 \
    -x 192.168.0.0/16 -x 172.16.0.0/12 -x 10.0.0.0/8
}
# usage: sshuttle-all ubuntu@orange.jangho.io -H
function sshuttle-all {
  sshuttle ${@:2} -r "$1" 0/0 -x $(echo "$1" | cut -d'@' -f2 | cut -d':' -f1)/32
}
alias sshuttle-mulan='sshuttle --dns -r mulan.snuspl.snu.ac.kr 192.168.1.0/24'

# local::lib
export PATH="$HOME/.perl5/bin${PATH:+:${PATH}}"
export PERL5LIB="$HOME/.perl5/lib/perl5${PERL5LIB:+:${PERL5LIB}}"
export PERL_LOCAL_LIB_ROOT="$HOME/.perl5${PERL_LOCAL_LIB_ROOT:+:${PERL_LOCAL_LIB_ROOT}}"
export PERL_MB_OPT="--install_base \"$HOME/.perl5\""
export PERL_MM_OPT="INSTALL_BASE=$HOME/.perl5"
export PERL_MM_USE_DEFAULT=1

# addins before loading plugins
while read -r addin
do
  source $addin
done <<<$(find -L $HOME/.setup/this -name "zshrc_addin_pre")

# Manage plugins
if [[ $MODE == '--manage-only' ]]
then
  zplug clean
  zplug update
  zplug install
  exit 0
fi
if [[ $MODE == '--install-only' ]]
then
  zplug install
  exit 0
fi
zplug check --verbose || zplug install
zplug load

# addins after loading plugins
while read -r addin
do
  source $addin
done <<<$(find -L $HOME/.setup/this -name "zshrc_addin_post")
